# Generated by Django 5.1.4 on 2025-09-01 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_alter_transmission_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commodity",
            unique_together={("site", "name")},
        ),
    ]





