# Generated by Django 5.2.4 on 2026-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
