# Generated by GPT-5.2 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_userverification_is_admin_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="is_admin_rejected",
            field=models.BooleanField(default=False),
        ),
    ]

